name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allow-failure }}

    strategy:
      fail-fast: false
      matrix:
        emacs-version:
          - 27-2
          - 28-2
          - 29-1
        allow-failure: [false]
        include:
          - emacs-version: 26-3
            allow-failure: true

    steps:
    - uses: actions/checkout@v4

    - name: Install Emacs ${{ matrix.emacs-version }}
      uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Install dependencies
      run: make install-deps test-deps

    - name: Build and test
      run: |
        echo org-version = $(make org-version)
        make byte-compile
        make run-tests
